[project]
name = "2025-cicd"
version = "0.1.0"
description = "Sample cicd"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
