name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update Channel API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.18
          cache: pip

      - name: Install uv
        run: pip install uv

      - name: Install requirements
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest .
